name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'modules/**'
      - 'environments/**'
      - 'lambda_src/**'

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  terraform:
    name: 'Terraform Lint, Plan & Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: github-actions

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform plan
        working-directory: environments/dev
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        working-directory: environments/dev
        run: terraform apply -auto-approve -var-file=terraform.tfvars
